logLevel: info
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: ""
credentials:
  enabled: false
controller:
  image:
    repository: "ghcr.io/babakzarrinbal/karpenter-provider-gcp"
    tag: "latest"
  settings:
    projectID: ""
    location: "europe-west4"
    clusterName: ""
